blank_issues_enabled: false
contact_links:
  - name: :bulb: Feature Request
    url: https://github.com/JuanRodenas/Pihole_list/discussions/categories/ideas
    about: Discuss ideas for new features or enhancements, it will be converted to GitHub issue when we commit to building those changes or are helping a community member contribute their own changes
  - name: :question: Ask a question
    url: https://github.com/JuanRodenas/Pihole_list/discussions/categories/general
    about: Ask questions and discuss with other community members.
